### PR TITLE
Add the -i option to ntthal

### PR DESCRIPTION
**Pull request by nh13**
This allows multiple queries to be performed via ntthal.

See: https://github.com/primer3-org/primer3/issues/12

### CODE REVIEW

**Comment by bioinfo-ut** [comment]
Our consortium's  general policy requires that all new functionalities should be covered by install-time tests. Please create some tests to test the new functionality.
We can't merge before that.
Triinu will send you valgrind output.

**Comment by nh13** [comment]
@bioinfo-ut any tips on writing tests for this functionality. This is my first PR so any suggestions would be useful.

**Comment by nh13** [comment]
@bioinfo-ut tests have been added:
1. Equivalent tests to the existing, but using the `-i` option.
2. Batching many queries in one batch using the `-i` option.

**Comment by bioinfo-ut** [comment]
Valgrind error report:
Unpack this .gz, run vgrep.pl (included) to see where the valgrind errors come from.

[ntthal.valgrind.output.tar.gz](https://github.com/primer3-org/primer3/files/3578699/ntthal.valgrind.output.tar.gz)

**Comment by nh13** [comment]
@bioinfo-ut can you assign to me so I can track this?

**Pull request merged**
