### PR TITLE
Add CI workflow for Ubuntu ARM64

### PR DESCRIPTION
**Pull request by martin-g**
Uses QEMU emulation to execute the build and tests in Ubuntu ARM64
Docker container

Related-to: #68

### CODE REVIEW

**Comment by martin-g** [comment]
CI result could be seen at https://github.com/martin-g/primer3/runs/7765454528?check_suite_focus=true

**Comment by martin-g** [comment]
Any feedback on the PR ?

**Comment by untergasser** [comment]
Hi,

it is great and I will include it. I was on holidays and I am currently busy with other projects with a tight deadline. But I will do this once I work on primer3. Thank you for creating this.

Best,
Andreas

**Comment by martin-g** [comment]
Thanks for the answer, @untergasser !
I am glad you find it useful!

**Comment by emiliofernandes** [comment]
This PR gave me confidence to start using Primer3 on Linux aarch64! :-)
I hope it is merged soon!

**Comment by untergasser** [comment]
I looked at this again. We support Windows, Linux and MacOS as default tests. I do not want to run QEMU in a docker image - my fear is that I spend time debugging this instead of working on Primer3. Therefore I tend not to include this.

What is the use case for Primer3 on aarch64? What machines run aarch64?

Best,
Andreas

**Comment by martin-g** [comment]
Hi @untergasser !

More and more cloud/server/HPC deployments are being moved to / started on Linux ARM64 due to:
* Lower power consumption: Ideal for mobile and battery-powered devices.
* Cost efficiency: Generally cheaper to produce due to simpler design.
* Heat efficiency: Generates less heat, reducing the need for cooling solutions.


Here is some info about the Linux ARM64 VM offerings by the major cloud providers:

1. AWS (Amazon Web Services) provides [Graviton](https://aws.amazon.com/ec2/graviton/) CPUs.
2. Microsoft Azure provides [VMs](https://techcommunity.microsoft.com/t5/azure-compute-blog/announcing-the-support-of-arm-based-vm-solutions-on-azure/ba-p/3968235) with Ampere CPUs. 
3. Google Cloud - [Tau and Tensor](https://cloud.google.com/compute/docs/instances/arm-on-compute) CPUs.
4. Oracle Cloud also provides [Ampere](https://blogs.oracle.com/linux/post/oracle-linux-cloud-images-now-available-for-the-arm-platform).
5. Huawei Cloud - VMs with [Kunpeng](https://forum.huawei.com/enterprise/en/comprehensive-comparison-of-docker-containerd-and-cri-o/thread/714614628014768128-667213860488228864) CPUs.


In [HPC](https://en.wikipedia.org/wiki/TOP500) few of the top 10 systems are based on ARM64:
* https://en.wikipedia.org/wiki/Fugaku_(supercomputer)
* https://www.nvidia.com/en-us/data-center/grace-cpu/


Despite the info above I'd be OK if you just close this PR without merging it!
The Mac OS CI job uses `macos-latest` that is a synonym to `macos-14`, i.e. Mac ARM64. It is not exactly the same as Linux ARM64 but it is very similar!

Also since recently the Bioconda project provides a linux-aarch64 [build](https://anaconda.org/bioconda/primer3) of primer3 - https://github.com/bioconda/bioconda-recipes/pull/48448. Bioconda project uses CircleCI to build natively on Linux ARM64 VMs.

**Comment by untergasser** [comment]
Hi @martin-g,

I see the potential. Lets close this pull request then for now.

If GitHub offers a native ARM64 platform, I will add this functionality. 

Ping me if I happen to oversee this.

Best, Andreas

**Pull request closed without merging**
